;**********************************************************************
; Description:
;   This defines the various tick lenghts that the Timer_Tick variable
;   contains.
;
;**********************************************************************
; Notes:
;
;
;**********************************************************************

; The following constants is defined for the Timer_Tick variable.
TimerTick_1ms       EQU 0x00
TimerTick_10ms      EQU 0x01
TimerTick_100ms     EQU 0x02
TimerTick_1000ms    EQU 0x03
TimerTick_10000ms   EQU 0x04
